export enum USER_MODEL_ERRORS {
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_TOKEN = 'INVALID TOKEN'
}

export enum APP_MODEL_ERRORS {
  APP_NAME_REQUIRED = 'APP_NAME_REQUIRED',
  EVENT_REQUIRED = 'EVENT_REQUIRED',
  SELECTOR_TYPE_REQUIRED = 'SELECTOR_TYPE_REQUIRED',
  SELECTOR_TYPE_INVALID = 'SELECTOR_TYPE_INVALID',
  SELECTOR_REQUIRED = 'SELECTOR_REQUIRED',
  TRIGGER_REQUIRED = 'TRIGGER_REQUIRED',
  MAX_APPS_REACHED = 'MAX_APPS_REACHED'
}

export enum EVENT_MODEL_ERRORS {
  APP_REQUIRED = 'APP_REQUIRED',
  USER_REQUIRED = 'USER_REQUIRED',
  EVENT_REQUIRED = 'EVENT_REQUIRED',
  CAPTURED_AT_REQUIRED = 'CAPTURED_AT_REQUIRED'
}

export enum EVENT_TYPES {
  internal = 1,
  external = 2,
  session = 3,
  'rule-based' = 4
}

export enum OTP_MESSAGES {
  INVALID = 'INVALID',
  EXPIRED = 'EXPIRED',
  ATTEMPTS_EXCEEDED = 'ATTEMPTS_EXCEEDED'
}

export enum BILLING_PERIOD {
  MONTHLY = 'm',
  YEARLY = 'y'
}

export enum ACCOUNT_STATUS {
  UNVERIFIED,
  ACTIVE,
  INACTIVE,
  SUSPENDED,
  DELETED
}

export enum APP_STATUS {
  ACTIVE,
  PAUSED,
  DELETED,
  SUSPENDED
}

export const TOTAL_TRIAL_EVENTS = 50000 // 50000 events
export const TOTAL_TRIAL_DURATION = 7 * 24 * 60 * 60 * 1000 // 7 days
export const OTP_EXPIRY = 10 * 60 * 1000 // 10 minutes
export const TOTAL_ALLOWED_INCORRECT_OTP_ATTEMPTS = 3
export const TOTAL_ALLOWED_USER_APPS = 100

export enum USER_CONTROLLER_ERROR_CODES {
  INVALID_EMAIL = 0x0101,
  INVALID_OTP = 0x0102,
  INCORRECT_OTP = 0x0103,
  OTP_EXPIRED = 0x0104,
  OTP_ATTEMPTS_EXCEEDED = 0x0105,
  USER_NOT_FOUND = 0x0106,
  USER_ALREADY_EXISTS = 0x0107,
  INVALID_AUTHORIZATION = 0x0108,
  INVALID_NAME = 0x0109,
  INVALID_PASSWORD = 0x010a
}

export enum APP_CONTROLLER_ERROR_CODES {
  APP_NAME_REQUIRED = 0x0201,
  APP_NAME_INVALID = 0x0202,
  INVALID_APP_DOMAIN = 0x0203,
  APP_NOT_FOUND = 0x0204,
  MAX_APPS_REACHED = 0x0205,
  EVENT_REQUIRED = 0x0206,
  SELECTOR_TYPE_REQUIRED = 0x0207,
  SELECTOR_TYPE_INVALID = 0x0208,
  SELECTOR_REQUIRED = 0x0209,
  TRIGGER_REQUIRED = 0x020a,
  INVALID_TEXT = 0x020b,
  INVALID_PAGE = 0x020c,
  INVALID_EVENT_IDS = 0x020d,
  INVALID_APP_ID = 0x02ff
}
