export const USER_MODEL_ERRORS = {
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID TOKEN'
}

export const APP_MODEL_ERRORS = {
  APP_NAME_REQUIRED: 'APP_NAME_REQUIRED',
  EVENT_REQUIRED: 'EVENT_REQUIRED',
  SELECTOR_TYPE_REQUIRED: 'SELECTOR_TYPE_REQUIRED',
  SELECTOR_TYPE_INVALID: 'SELECTOR_TYPE_INVALID',
  SELECTOR_REQUIRED: 'SELECTOR_REQUIRED',
  TRIGGER_REQUIRED: 'TRIGGER_REQUIRED',
  MAX_APPS_REACHED: 'MAX_APPS_REACHED'
}

export const EVENT_MODEL_ERRORS = {
  APP_REQUIRED: 'APP_REQUIRED',
  USER_REQUIRED: 'USER_REQUIRED',
  EVENT_REQUIRED: 'EVENT_REQUIRED'
}

export const EVENT_TYPES = {
  internal: 1,
  external: 2,
  session: 3,
  'tag-based': 4,
  1: 'internal',
  2: 'external',
  3: 'session',
  4: 'tag-based'
}

export const OTP_MESSAGES = {
  INVALID: 'INVALID',
  EXPIRED: 'EXPIRED',
  ATTEMPTS_EXCEEDED: 'ATTEMPTS_EXCEEDED'
}

export const BILLING_PERIOD = {
  MONTHLY: 'm',
  YEARLY: 'y',
  m: 'MONTHLY',
  y: 'YEARLY'
}

export const ACCOUNT_STATUS = {
  UNVERIFIED: 0,
  ACTIVE: 1,
  SUSPENDED: 3,
  DELETED: 4
}

export const ACCOUNT_STATUS_CODES = {
  0: 'UNVERIFIED',
  1: 'ACTIVE',
  3: 'SUSPENDED',
  4: 'DELETED'
}

export const APP_STATUS = {
  ACTIVE: 0,
  PAUSED: 1,
  DELETED: 2,
  SUSPENDED: 3
}

export const APP_STATUS_CODES = {
  0: 'ACTIVE',
  1: 'PAUSED',
  2: 'DELETED',
  3: 'SUSPENDED'
}

export const TOTAL_TRIAL_EVENTS = 1000 // 1000 events
export const TOTAL_TRIAL_DURATION = 7 * 24 * 60 * 60 * 1000 // 7 days
export const OTP_EXPIRY = 10 * 60 * 1000 // 10 minutes
export const TOTAL_ALLOWED_INCORRECT_OTP_ATTEMPTS = 5
export const TOTAL_ALLOWED_USER_APPS = 10

export const USER_CONTROLLER_ERROR_CODES = {
  INVALID_EMAIL: 0x01001,
  INVALID_OTP: 0x01002,
  INCORRECT_OTP: 0x01003,
  OTP_EXPIRED: 0x01004,
  OTP_ATTEMPTS_EXCEEDED: 0x01005,
  USER_NOT_FOUND: 0x01006,
  USER_ALREADY_EXISTS: 0x01007
}

export const APP_CONTROLLER_ERROR_CODES = {
  APP_NAME_REQUIRED: 0x02001,
  INVALID_APP_DOMAIN: 0x02002,
  APP_NOT_FOUND: 0x02003,
  MAX_APPS_REACHED: 0x02004,
  EVENT_REQUIRED: 0x02005,
  SELECTOR_TYPE_REQUIRED: 0x02006,
  SELECTOR_TYPE_INVALID: 0x02007,
  SELECTOR_REQUIRED: 0x02008,
  TRIGGER_REQUIRED: 0x02009
}
